spring:
  cloud:
    gateway:
      routes:
        - id: products-api
          uri: lb://products-api
          predicates:
            - Path=/api/productos/**
            - Header= token, \d+
            - Method=GET, POST
            - Query=color, verde
#            - Cookie=color, azul
          filters:
            - StripPrefix=2
            - EjemploCookie=GatewayFilterFactory personalizado, usuario, UdemyPruebas
        - id: items-api
          uri: lb://items-api
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request, 123456
            - AddResponseHeader=token-response, 12345678
            - SetResponseHeader=Content-Type, text/plain
            - AddRequestParameter=nombre, Samsung